### ISSUE TITLE
Message on internal server error is not helpful

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1009]
I just ran into an internal server error on Edmond. The page returned says

>> Notification
>> Sorry, this should not have happened. An internal server error occurred. Please go back to the homepage and try again.

I think this is unhelpful to the point of being a bug. Why should I try again? To reproduce the error? If so, shouldn't there be information how to report the error? But do I have to report the error? Couldn't it be logged? And if so, shouldn't the message say as much?

So I see two options: Either include information how to report errors/bugs, or include a statement that the error is logged and will be looked into anyway.

**Comment by bastienMPDL** [comment]
WE are aware of it and we plan to improve it as soon as possible (i.e in the next sprints).

**Comment by natasab** [comment]
Closed as there is general issue and not precisely where it happened. Dev-imeji is fixed, Edmond will be fixed after decision from the Edmond team.

**Comment by xrotwang** [comment]
I think we need a policy about how issues are used. Right now it seems they are used to track tasks of the MPDL development team. E.g. issues are closed when the team thinks work has been done to address the issue. This is not really transparent to the outside world, i.e. neither can I see how the issue was addressed, since there is no commit linked, nor whether a more "general issue" has been opened.

Ideally - from a community members point of view - all commits which address/close issues should say so in the commit message, and the issues should be closed automatically when the corresponding code from the MPDL fork is merged into the community repos.

Maybe the MPDL team should use issues in its own fork to manage development tasks within the team?

**Comment by natasab** [comment]
This issue was not addressed with particular piece of code which is committed and closed also at imeji-community repo through the MPDL fork. It addresses Edmond and does not have particular details about how and when it happened, so that we can track it. Continuous improvements are provided in meantime and addressed through other similarly reported issues. That is the reson it is closed. 
Issue management for MPDL fork issues will be most likely moved to the MPDL fork in future.
