### ISSUE TITLE
Ambigious file type recognition by imeji

### ISSUE THREAD

**Issue by vmakarenko** [imeji-community/imeji#1019]
imeji uses extension of uploaded file for following internal file procession like thumbnail generation,
data viewer service, etc. This behavior is errors and security problems prone. Eg., file of any content can be postfixed with an imeji allowed extension (see imeji.upload.whitelist and imeji.upload.blacklist) and then uploaded in imeji. 
Possible solution: Always use tika for file type detection and reject file which has type is not allowed in imeji. New types like bioformats SWC type can be easily registered in tika:
http://tika.apache.org/1.7/parser_guide.html#Add_your_MIME-Type. Allowed/not Allowed types can be enumerated in imeji.upload.whitelist and imeji.upload.blacklist properties.

Tika supported formats: http://tika.apache.org/1.7/formats.html

**Comment by xrotwang** [comment]
I think a decision in this matter requires a shared understanding of potential attack vectors. E.g. is there really a threat that malicious content may be uploaded, considering that most imeji installations will presumably have a set of well-known users who are allowed to upload (most probably even users with contractual obligations with the institution hosting imeji)?

I admit, though, that guessing mimetypes by filename extensions is error prone, which is why I advocate to allow setting the mimetype explicitely via the API.

**Comment by bastienMPDL** [comment]
Now is done via Tika
