### ISSUE TITLE
API: Inconsistent naming of workflow states/transitions

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1053]
Whereas a `release` operation leads to a status `RELEASED`, `discard` leads to `WITHDRAWN`. I think this should be fixed because it is confusing, and either leads to cognitive overhead for each user or to more code in client libraries.

**Comment by natasab** [comment]
In addition, create operation leads to status "PENDING". 
I guess the consistency of naming states very similar (or linguistically derived)  from the workflow action name is simply nice to have. 
It should be well documented however,

**Comment by natasab** [comment]
Would say as quick and dirty :) - but no inconsistent.. 
REST API provides following value in following form for status

"modifiedDate": "2015-04-16T15:50:22 +0200",
  "versionDate": "",
  "status": "RELEASED",
  "version": 0,
  "discardComment": "",


The logic should be changed, so that it takes as a parameter status=RELEASED or status=WITHDRAWN ... 

That will be consistent with the REST API as well. Does it make sense?

**Comment by xrotwang** [comment]
Distinguishing between transition and state, i.e. between verb and adjective seems sensible for me, because the workflow is a state machine, after all.

**Comment by natasab** [comment]
closing this issue. addressed on other places.
