### ISSUE TITLE
Downloads on selected Items

### ISSUE THREAD

**Issue by fsajp** [imeji-community/imeji#1063]
When logged-in user go to "Items", select several items, and then click "Download", then not only the selected items are downloaded, but ALL available items.
(This is the same behavior for all download options -> zip/RDF/imeji format)

Is this an intended behavior?

**Comment by bastienMPDL** [comment]
Yes it is. But I understand it might be a litte bit confusing.
There is actually no way to download only the selected pictures.
I will put this issue as feature request

**Comment by natasab** [comment]
Implemented. If there are selected items, they will be automatically downloaded. If there are no selected items, all items in the selected context (collection, album) will be downloaded (this was already implementd). 
If user is in Items context and there are no selected items, all items visible to  the user of the instance will be downloaded (would actually reconsider this because of performance and load, should be probably done in different manner).

**Comment by vmakarenko** [comment]
Tested @ Ubuntu, FF 38.0, Chrome 43.0.2357.130 (64-bit), works fine.
